<?php

// ACF Custom Fields for Membership Plans

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5ef17a4b49297',
		'title' => 'Plan Details',
		'fields' => array(
			array(
				'key' => 'field_5ef17aac6fbbc',
				'label' => 'Price',
				'name' => 'price',
				'type' => 'text',
				'instructions' => 'Price in Australian Dollars (no dollar sign)',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '$',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ef17b6c0e4cb',
				'label' => 'Plan Duration',
				'name' => 'duration',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'month' => 'Monthly',
					'year' => 'Annual',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ef17bc90e4cc',
				'label' => 'Plan Type',
				'name' => 'type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'individual' => 'Individual',
					'team' => 'Team',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ef194246189a',
				'label' => 'Features',
				'name' => 'features',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'field_5ef194386189b',
						'label' => 'Access to Content',
						'name' => 'content',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'yes' => 'Yes',
							'no' => 'No',
						),
						'allow_null' => 1,
						'other_choice' => 1,
						'save_other_choice' => 0,
						'default_value' => 'no',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5ef2dac14fec2',
						'label' => 'Newsletter',
						'name' => 'newsletter',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'yes' => 'Yes',
							'no' => 'No',
						),
						'allow_null' => 1,
						'other_choice' => 1,
						'save_other_choice' => 0,
						'default_value' => 'no',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5ef2dacf4fec3',
						'label' => 'Event 1',
						'name' => 'event_1',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'yes' => 'Yes',
							'no' => 'No',
						),
						'allow_null' => 1,
						'other_choice' => 1,
						'save_other_choice' => 0,
						'default_value' => 'no',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5ef2daf14fec5',
						'label' => 'Community Forum',
						'name' => 'forum',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'yes' => 'Yes',
							'no' => 'No',
						),
						'allow_null' => 1,
						'other_choice' => 1,
						'save_other_choice' => 0,
						'default_value' => 'no',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
					array(
						'key' => 'field_5ef2db034fec6',
						'label' => 'Stickers',
						'name' => 'stickers',
						'type' => 'radio',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'yes' => 'Yes',
							'no' => 'No',
						),
						'allow_null' => 1,
						'other_choice' => 1,
						'save_other_choice' => 0,
						'default_value' => 'no',
						'layout' => 'horizontal',
						'return_format' => 'value',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'plans',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'slug',
			6 => 'author',
			7 => 'format',
			8 => 'page_attributes',
			9 => 'featured_image',
			10 => 'categories',
			11 => 'tags',
		),
		'active' => true,
		'description' => '',
	));
	
	endif;

?>